#!/usr/bin/env ruby
require 'rubygems'

require 'bundler'
Bundler.require


CONFIG_FILE = File.join(File.dirname(__FILE__), '..', 'config.yml')
$: << File.join(File.dirname(__FILE__), '..', 'lib')
require "hudhub"

require 'irb'
require 'pp'
IRB.start
